//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoTheThao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONHANG
    {
        public int MADH { get; set; }
        public int ID_BIENTHE { get; set; }
        public int SOLUONG { get; set; }
        public decimal DONGIA { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
    
        public virtual BIENTHESP BIENTHESP { get; set; }
        public virtual DONHANG DONHANG { get; set; }
    }
}
