//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoTheThao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public int ID { get; set; }
        public string MADG { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<int> MASP { get; set; }
        public int SOSAO { get; set; }
        public string BINHLUAN { get; set; }
        public Nullable<System.DateTime> NGAYDG { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
