//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoTheThao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.LICHSUDONHANGs = new HashSet<LICHSUDONHANG>();
            this.LICHSUTHANHTOANs = new HashSet<LICHSUTHANHTOAN>();
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
        }
    
        public int ID { get; set; }
        public string MADH { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<int> MAGG { get; set; }
        public decimal TONGTIEN { get; set; }
        public string PHUONGTHUC { get; set; }
        public string TRANGTHAI { get; set; }
        public string DIACHI { get; set; }
    
        public virtual GIAMGIA GIAMGIA { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUDONHANG> LICHSUDONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUTHANHTOAN> LICHSUTHANHTOANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
    }
}
