//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoTheThao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAMGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAMGIA()
        {
            this.DONHANGs = new HashSet<DONHANG>();
        }
    
        public int ID { get; set; }
        public string MAGG { get; set; }
        public Nullable<int> MAKH { get; set; }
        public string TENGG { get; set; }
        public Nullable<decimal> PHANTRAM { get; set; }
        public Nullable<decimal> SOTIENGIAM { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public Nullable<decimal> DIEUKIEN { get; set; }
        public Nullable<int> SOLUOT { get; set; }
        public string TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
