//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoTheThao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHSUDONHANG
    {
        public int ID { get; set; }
        public string MALSDH { get; set; }
        public Nullable<int> MADH { get; set; }
        public Nullable<System.DateTime> NGAYTHAYDOI { get; set; }
        public string TRANGTHAI_CU { get; set; }
        public string TRANGTHAI_MOI { get; set; }
        public string GHICHU { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
    }
}
