//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoTheThao.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLQAEntities : DbContext
    {
        public QLQAEntities()
            : base("name=QLQAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BIENTHESP> BIENTHESPs { get; set; }
        public virtual DbSet<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual DbSet<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        public virtual DbSet<DANHGIA> DANHGIAs { get; set; }
        public virtual DbSet<DONHANG> DONHANGs { get; set; }
        public virtual DbSet<GIAMGIA> GIAMGIAs { get; set; }
        public virtual DbSet<GIOHANG> GIOHANGs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LICHSUDONHANG> LICHSUDONHANGs { get; set; }
        public virtual DbSet<LICHSUTHANHTOAN> LICHSUTHANHTOANs { get; set; }
        public virtual DbSet<LOAI> LOAIs { get; set; }
        public virtual DbSet<MONTT> MONTTs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<SIZE> SIZEs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THUONGHIEU> THUONGHIEUx { get; set; }
        public virtual DbSet<YEUTHICH> YEUTHICHes { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_DangKy(string ho, string ten, string sDT, string email, string matKhau)
        {
            var hoParameter = ho != null ?
                new ObjectParameter("Ho", ho) :
                new ObjectParameter("Ho", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DangKy", hoParameter, tenParameter, sDTParameter, emailParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<sp_DangNhap_Result> sp_DangNhap(string email, string matKhau)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DangNhap_Result>("sp_DangNhap", emailParameter, matKhauParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_FilterByTenMonTT(string tENMON)
        {
            var tENMONParameter = tENMON != null ?
                new ObjectParameter("TENMON", tENMON) :
                new ObjectParameter("TENMON", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_FilterByTenMonTT", tENMONParameter);
        }
    
        public virtual int sp_FilterByTenThuongHieu(string tenTH)
        {
            var tenTHParameter = tenTH != null ?
                new ObjectParameter("TenTH", tenTH) :
                new ObjectParameter("TenTH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_FilterByTenThuongHieu", tenTHParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_SuaSanPham(string mASP, string tENSP, Nullable<int> mATH, Nullable<decimal> gIA, string cOLOR, Nullable<int> sOLUONG, Nullable<int> mALOAI, Nullable<int> mAMON, string aVATAR, string mOTA)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var mATHParameter = mATH.HasValue ?
                new ObjectParameter("MATH", mATH) :
                new ObjectParameter("MATH", typeof(int));
    
            var gIAParameter = gIA.HasValue ?
                new ObjectParameter("GIA", gIA) :
                new ObjectParameter("GIA", typeof(decimal));
    
            var cOLORParameter = cOLOR != null ?
                new ObjectParameter("COLOR", cOLOR) :
                new ObjectParameter("COLOR", typeof(string));
    
            var sOLUONGParameter = sOLUONG.HasValue ?
                new ObjectParameter("SOLUONG", sOLUONG) :
                new ObjectParameter("SOLUONG", typeof(int));
    
            var mALOAIParameter = mALOAI.HasValue ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(int));
    
            var mAMONParameter = mAMON.HasValue ?
                new ObjectParameter("MAMON", mAMON) :
                new ObjectParameter("MAMON", typeof(int));
    
            var aVATARParameter = aVATAR != null ?
                new ObjectParameter("AVATAR", aVATAR) :
                new ObjectParameter("AVATAR", typeof(string));
    
            var mOTAParameter = mOTA != null ?
                new ObjectParameter("MOTA", mOTA) :
                new ObjectParameter("MOTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaSanPham", mASPParameter, tENSPParameter, mATHParameter, gIAParameter, cOLORParameter, sOLUONGParameter, mALOAIParameter, mAMONParameter, aVATARParameter, mOTAParameter);
        }
    
        public virtual int sp_ThemSanPham(string tENSP, Nullable<int> mATH, Nullable<decimal> gIA, string cOLOR, Nullable<int> sOLUONG, Nullable<int> mALOAI, Nullable<int> mAMON, string aVATAR, string mOTA)
        {
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var mATHParameter = mATH.HasValue ?
                new ObjectParameter("MATH", mATH) :
                new ObjectParameter("MATH", typeof(int));
    
            var gIAParameter = gIA.HasValue ?
                new ObjectParameter("GIA", gIA) :
                new ObjectParameter("GIA", typeof(decimal));
    
            var cOLORParameter = cOLOR != null ?
                new ObjectParameter("COLOR", cOLOR) :
                new ObjectParameter("COLOR", typeof(string));
    
            var sOLUONGParameter = sOLUONG.HasValue ?
                new ObjectParameter("SOLUONG", sOLUONG) :
                new ObjectParameter("SOLUONG", typeof(int));
    
            var mALOAIParameter = mALOAI.HasValue ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(int));
    
            var mAMONParameter = mAMON.HasValue ?
                new ObjectParameter("MAMON", mAMON) :
                new ObjectParameter("MAMON", typeof(int));
    
            var aVATARParameter = aVATAR != null ?
                new ObjectParameter("AVATAR", aVATAR) :
                new ObjectParameter("AVATAR", typeof(string));
    
            var mOTAParameter = mOTA != null ?
                new ObjectParameter("MOTA", mOTA) :
                new ObjectParameter("MOTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemSanPham", tENSPParameter, mATHParameter, gIAParameter, cOLORParameter, sOLUONGParameter, mALOAIParameter, mAMONParameter, aVATARParameter, mOTAParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
