//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoTheThao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.BIENTHESPs = new HashSet<BIENTHESP>();
            this.DANHGIAs = new HashSet<DANHGIA>();
            this.YEUTHICHes = new HashSet<YEUTHICH>();
        }
    
        public int ID { get; set; }
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> MATH { get; set; }
        public decimal GIA { get; set; }
        public string COLOR { get; set; }
        public Nullable<int> MALOAI { get; set; }
        public Nullable<int> MAMON { get; set; }
        public string AVATAR { get; set; }
        public string MOTA { get; set; }
        public string TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENTHESP> BIENTHESPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual MONTT MONTT { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEUTHICH> YEUTHICHes { get; set; }
    }
}
