//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDoTheThao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEUTHICH
    {
        public int MAND { get; set; }
        public int MASP { get; set; }
        public Nullable<System.DateTime> NGAYTHEM { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
